version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT_HOST}:3306"
    volumes:
      - ./dummy_data.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 20


  postgres:
    image: postgres:14
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
    - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
    volumes:
      - ./dummy_data.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elt:
    build:
      context: ./elt-data
    container_name: elt-data
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
    - .env

  api:
    build:
      context: ./task-api
    container_name: task_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env